name = "lorefell-table"
main = "worker.js"
compatibility_date = "2025-01-01"
workers_dev = true

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "TableRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TableRoom"]
