// scripts/build.js
// Generates the two runtime copies of the rule interpreter from scripts/rules.core.js,
// then checks that the kernel loads rules.js externally instead of carrying its own copy.
// Run: node scripts/build.js

const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const corePath = path.join(root, "scripts", "rules.core.js");
const docsRules = path.join(root, "docs", "rules.js");
const veloRules = path.join(root, "velo", "backend", "rules.js");
const kernel = path.join(root, "docs", "forgemaster.html");

const core = fs.readFileSync(corePath, "utf8").trimEnd();

const banner = "// GENERATED by scripts/build.js from scripts/rules.core.js. Do not edit by hand.\n";

// Browser + Node copy. Exposes window.LF.validate for the kernel and module.exports for Node.
const browserFooter = `
;(function (root) {
  var api = { validate: validate, meets: meets, describe: describe, exactMatch: exactMatch };
  if (typeof module !== "undefined" && module.exports) { module.exports = api; }
  root.LF = root.LF || {};
  root.LF.validate = validate;
})(typeof window !== "undefined" ? window : globalThis);
`;
fs.writeFileSync(docsRules, banner + core + "\n" + browserFooter);

// Velo backend copy. ESM export so forge.jsw can: import { validate } from 'backend/rules.js'
const veloFooter = `\nexport { validate, meets, describe, exactMatch };\n`;
fs.writeFileSync(veloRules, banner + core + "\n" + veloFooter);

// Drift guard. The kernel must load the shared file and must not define its own validate().
const html = fs.readFileSync(kernel, "utf8");
const problems = [];
if (html.indexOf('src="./rules.js"') === -1) {
  problems.push('docs/forgemaster.html does not load ./rules.js');
}
if (/function\s+validate\s*\(/.test(html)) {
  problems.push('docs/forgemaster.html still defines its own validate(); it should use the shared rules.js');
}
if (problems.length) {
  console.error("Build drift check failed:");
  problems.forEach(function (p) { console.error("  - " + p); });
  process.exit(1);
}

console.log("Built docs/rules.js and velo/backend/rules.js from rules.core.js. Kernel uses the shared copy.");
