// Canon lorebounds for BondForge. One-time seed source for the Creations collection.
// Edit here only if you want to reseed. Day to day, manage canon in the CMS.

export const CANON_BONDS = [
  {
    "forgeKey": "bondforge",
    "kind": "bond",
    "creationName": "The Aerostrix",
    "canonStatus": "canon",
    "voteCount": 0,
    "creatorName": "Skyvault Studios",
    "shorthand": "When a Fell makes an attack, that attack is a Lucky Roll.",
    "fullText": "Aspect: Augury\nInitial. When a Fell makes an attack, that attack is a Lucky Roll.\nBranching, keep one: The target's Evasion becomes 0 against that attack. OR The Fell adds the lorebound owner's Precision to its own for that attack.\nCrown, keep one: Add a second Lucky die to that attack. OR The target's Evade against that attack is an Unlucky Roll.",
    "imageUrl": "",
    "payload": "{\"meta\": {\"world\": \"Sellenia\", \"role\": \"Bends fortune so a Fell's strike lands true.\", \"archetype\": \"control\", \"aspectName\": \"Augury\", \"initial\": \"When a Fell makes an attack, that attack is a Lucky Roll.\", \"branches\": [\"The target's Evasion becomes 0 against that attack.\", \"The Fell adds the lorebound owner's Precision to its own for that attack.\"], \"crowns\": [\"Add a second Lucky die to that attack.\", \"The target's Evade against that attack is an Unlucky Roll.\"], \"creator\": \"Skyvault Studios\"}}"
  },
  {
    "forgeKey": "bondforge",
    "kind": "bond",
    "creationName": "The Alkagoo",
    "canonStatus": "canon",
    "voteCount": 0,
    "creatorName": "Skyvault Studios",
    "shorthand": "When a target's Tier 1 spell or ability resolves, copy it into the lorebound owner's inventory as a potion for a spell or a tablet for an ability.",
    "fullText": "Aspect: Distillation\nInitial. When a target's Tier 1 spell or ability resolves, copy it into the lorebound owner's inventory as a potion for a spell or a tablet for an ability.\nBranching, keep one: Upgrade the capture to any spell or ability of your choosing in the next highest Tier. OR Create a second copy.\nCrown, keep one: Upgrade the capture to any spell or ability of your choosing in the next highest Tier. OR Create a second copy.",
    "imageUrl": "",
    "payload": "{\"meta\": {\"world\": \"Akkoroka\", \"role\": \"Distills a spent spell or ability into a potion or tablet to use later.\", \"archetype\": \"negation\", \"aspectName\": \"Distillation\", \"initial\": \"When a target's Tier 1 spell or ability resolves, copy it into the lorebound owner's inventory as a potion for a spell or a tablet for an ability.\", \"branches\": [\"Upgrade the capture to any spell or ability of your choosing in the next highest Tier.\", \"Create a second copy.\"], \"crowns\": [\"Upgrade the capture to any spell or ability of your choosing in the next highest Tier.\", \"Create a second copy.\"], \"creator\": \"Skyvault Studios\"}}"
  },
  {
    "forgeKey": "bondforge",
    "kind": "bond",
    "creationName": "The Aquafin",
    "canonStatus": "canon",
    "voteCount": 0,
    "creatorName": "Skyvault Studios",
    "shorthand": "When a target lands an attack, prevent it from gaining a Charge.",
    "fullText": "Aspect: Siphon\nInitial. When a target lands an attack, prevent it from gaining a Charge.\nBranching, keep one: Give the prevented Charge to the Fell that was attacked. OR Give the prevented Charge to the lorebound owner.\nCrown, keep one: Remove all additional Charges from the target. OR Restore the lorebound owner to maximum Charges.",
    "imageUrl": "",
    "payload": "{\"meta\": {\"world\": \"Neriad\", \"role\": \"Robs a foe of the Charge its attack would earn.\", \"archetype\": \"empower\", \"aspectName\": \"Siphon\", \"initial\": \"When a target lands an attack, prevent it from gaining a Charge.\", \"branches\": [\"Give the prevented Charge to the Fell that was attacked.\", \"Give the prevented Charge to the lorebound owner.\"], \"crowns\": [\"Remove all additional Charges from the target.\", \"Restore the lorebound owner to maximum Charges.\"], \"creator\": \"Skyvault Studios\"}}"
  },
  {
    "forgeKey": "bondforge",
    "kind": "bond",
    "creationName": "The Boreal",
    "canonStatus": "canon",
    "voteCount": 0,
    "creatorName": "Skyvault Studios",
    "shorthand": "When a physical attack hits a Fell, prevent Base damage equal to the lorebound owner's Vigor.",
    "fullText": "Aspect: Succor\nInitial. When a physical attack hits a Fell, prevent Base damage equal to the lorebound owner's Vigor.\nBranching, keep one: Convert the prevented damage into Temporary Vitality for the lorebound owner. OR Convert the prevented damage into Temporary Vitality for the Fell that was hit.\nCrown, keep one: The prevented damage restores Current Vitality first, and overflow is converted to Temporary Vitality. OR Prevent and convert double the Base damage.",
    "imageUrl": "",
    "payload": "{\"meta\": {\"world\": \"Mortavia\", \"role\": \"Softens a physical blow and turns what it spares into vitality.\", \"archetype\": \"mitigation\", \"aspectName\": \"Succor\", \"initial\": \"When a physical attack hits a Fell, prevent Base damage equal to the lorebound owner's Vigor.\", \"branches\": [\"Convert the prevented damage into Temporary Vitality for the lorebound owner.\", \"Convert the prevented damage into Temporary Vitality for the Fell that was hit.\"], \"crowns\": [\"The prevented damage restores Current Vitality first, and overflow is converted to Temporary Vitality.\", \"Prevent and convert double the Base damage.\"], \"creator\": \"Skyvault Studios\"}}"
  },
  {
    "forgeKey": "bondforge",
    "kind": "bond",
    "creationName": "The Cawmarch",
    "canonStatus": "canon",
    "voteCount": 0,
    "creatorName": "Skyvault Studios",
    "shorthand": "When a Fell gains an Affliction, negate it.",
    "fullText": "Aspect: Scour\nInitial. When a Fell gains an Affliction, negate it.\nBranching, keep one: Apply the negated Affliction to the attacker. OR Store the Affliction as a Glyph in the lorebound owner's inventory.\nCrown, keep one: Apply a copy of the Affliction to every enemy in the lorebound's Mobility range. OR Remove every Affliction from that Fell.",
    "imageUrl": "",
    "payload": "{\"meta\": {\"world\": \"Mortavia\", \"role\": \"Scours an Affliction from a Fell before it sets in.\", \"archetype\": \"control\", \"aspectName\": \"Scour\", \"initial\": \"When a Fell gains an Affliction, negate it.\", \"branches\": [\"Apply the negated Affliction to the attacker.\", \"Store the Affliction as a Glyph in the lorebound owner's inventory.\"], \"crowns\": [\"Apply a copy of the Affliction to every enemy in the lorebound's Mobility range.\", \"Remove every Affliction from that Fell.\"], \"creator\": \"Skyvault Studios\"}}"
  },
  {
    "forgeKey": "bondforge",
    "kind": "bond",
    "creationName": "The Drakelith",
    "canonStatus": "canon",
    "voteCount": 0,
    "creatorName": "Skyvault Studios",
    "shorthand": "When a Fell makes any roll, that roll is a Lucky Roll.",
    "fullText": "Aspect: Boon\nInitial. When a Fell makes any roll, that roll is a Lucky Roll.\nBranching, keep one: Add a second Lucky die to the roll. OR If that roll is a Fellmark, double its effect.\nCrown, keep one: Every Fell in the lorebound's Mobility range becomes Lucky (its rolls are Lucky Rolls until it takes damage). OR At the end of the battle, every Fell in the lorebound's Mobility range adds a Lucky die to their treasure rolls.",
    "imageUrl": "",
    "payload": "{\"meta\": {\"world\": \"Burhallow\", \"role\": \"Turns any roll a Fell makes into a stroke of luck.\", \"archetype\": \"control\", \"aspectName\": \"Boon\", \"initial\": \"When a Fell makes any roll, that roll is a Lucky Roll.\", \"branches\": [\"Add a second Lucky die to the roll.\", \"If that roll is a Fellmark, double its effect.\"], \"crowns\": [\"Every Fell in the lorebound's Mobility range becomes Lucky (its rolls are Lucky Rolls until it takes damage).\", \"At the end of the battle, every Fell in the lorebound's Mobility range adds a Lucky die to their treasure rolls.\"], \"creator\": \"Skyvault Studios\"}}"
  },
  {
    "forgeKey": "bondforge",
    "kind": "bond",
    "creationName": "The Felionis",
    "canonStatus": "canon",
    "voteCount": 0,
    "creatorName": "Skyvault Studios",
    "shorthand": "When an enemy's spell targets a Fell, the spell is an Unlucky Roll.",
    "fullText": "Aspect: Aegis\nInitial. When an enemy's spell targets a Fell, the spell is an Unlucky Roll.\nBranching, keep one: If the spell still succeeds, prevent Bonus damage equal to the lorebound owner's Resistance. OR If the spell fails, it resolves on the caster instead.\nCrown, keep one: If the spell fails, the caster gains the Disrupted Affliction (its spells automatically fail unless a Fellmark is rolled). OR Every enemy in the lorebound's Mobility range gains the Unlucky Affliction (all its rolls become Unlucky).",
    "imageUrl": "",
    "payload": "{\"meta\": {\"world\": \"Shervinaw\", \"role\": \"Sours hostile magic aimed at a Fell so it falters.\", \"archetype\": \"mitigation\", \"aspectName\": \"Aegis\", \"initial\": \"When an enemy's spell targets a Fell, the spell is an Unlucky Roll.\", \"branches\": [\"If the spell still succeeds, prevent Bonus damage equal to the lorebound owner's Resistance.\", \"If the spell fails, it resolves on the caster instead.\"], \"crowns\": [\"If the spell fails, the caster gains the Disrupted Affliction (its spells automatically fail unless a Fellmark is rolled).\", \"Every enemy in the lorebound's Mobility range gains the Unlucky Affliction (all its rolls become Unlucky).\"], \"creator\": \"Skyvault Studios\"}}"
  },
  {
    "forgeKey": "bondforge",
    "kind": "bond",
    "creationName": "The Grimgrit",
    "canonStatus": "canon",
    "voteCount": 0,
    "creatorName": "Skyvault Studios",
    "shorthand": "When a Fell is hit, deal Base damage to the attacker.",
    "fullText": "Aspect: Reprisal\nInitial. When a Fell is hit, deal Base damage to the attacker.\nBranching, keep one: Also apply a Combat Effect of your choice to the attacker. OR Deal Bonus damage to the attacker as well.\nCrown, keep one: Deal the damage to every enemy in the lorebound's Mobility range. OR Double all damage dealt.",
    "imageUrl": "",
    "payload": "{\"meta\": {\"world\": \"Kwuhara\", \"role\": \"Answers a blow against a Fell with one of its own.\", \"archetype\": \"retort\", \"aspectName\": \"Reprisal\", \"initial\": \"When a Fell is hit, deal Base damage to the attacker.\", \"branches\": [\"Also apply a Combat Effect of your choice to the attacker.\", \"Deal Bonus damage to the attacker as well.\"], \"crowns\": [\"Deal the damage to every enemy in the lorebound's Mobility range.\", \"Double all damage dealt.\"], \"creator\": \"Skyvault Studios\"}}"
  },
  {
    "forgeKey": "bondforge",
    "kind": "bond",
    "creationName": "The Hexarach",
    "canonStatus": "canon",
    "voteCount": 0,
    "creatorName": "Skyvault Studios",
    "shorthand": "When a Fell casts a spell, it automatically succeeds.",
    "fullText": "Aspect: Weave\nInitial. When a Fell casts a spell, it automatically succeeds.\nBranching, keep one: Swap the spell for another spell of your choosing in the same Tier. OR Duplicate the spell's effect onto another target.\nCrown, keep one: A second spell of your choosing in the same Tier is also cast and automatically succeeds. OR Spread the spell's effect to any targets you choose within the lorebound's Mobility range.",
    "imageUrl": "",
    "payload": "{\"meta\": {\"world\": \"Vyrathis\", \"role\": \"Makes a Fell's spell take hold without fail.\", \"archetype\": \"empower\", \"aspectName\": \"Weave\", \"initial\": \"When a Fell casts a spell, it automatically succeeds.\", \"branches\": [\"Swap the spell for another spell of your choosing in the same Tier.\", \"Duplicate the spell's effect onto another target.\"], \"crowns\": [\"A second spell of your choosing in the same Tier is also cast and automatically succeeds.\", \"Spread the spell's effect to any targets you choose within the lorebound's Mobility range.\"], \"creator\": \"Skyvault Studios\"}}"
  },
  {
    "forgeKey": "bondforge",
    "kind": "bond",
    "creationName": "The Lumitoad",
    "canonStatus": "canon",
    "voteCount": 0,
    "creatorName": "Skyvault Studios",
    "shorthand": "When an enemy uses its Act, it loses its React.",
    "fullText": "Aspect: Forfeit\nInitial. When an enemy uses its Act, it loses its React.\nBranching, keep one: The enemy also gains a Combat Effect at random. OR Give the lost React to a Fell within the lorebound's Mobility range.\nCrown, keep one: The enemy's Act is negated entirely. OR Apply an Affliction at random to the enemy.",
    "imageUrl": "",
    "payload": "{\"meta\": {\"world\": \"Mireth\", \"role\": \"Strips a foe of its React the moment it commits to an Act.\", \"archetype\": \"control\", \"aspectName\": \"Forfeit\", \"initial\": \"When an enemy uses its Act, it loses its React.\", \"branches\": [\"The enemy also gains a Combat Effect at random.\", \"Give the lost React to a Fell within the lorebound's Mobility range.\"], \"crowns\": [\"The enemy's Act is negated entirely.\", \"Apply an Affliction at random to the enemy.\"], \"creator\": \"Skyvault Studios\"}}"
  },
  {
    "forgeKey": "bondforge",
    "kind": "bond",
    "creationName": "The Mordel",
    "canonStatus": "canon",
    "voteCount": 0,
    "creatorName": "Skyvault Studios",
    "shorthand": "When a physical attack hits a Fell, prevent Bonus damage equal to the lorebound owner's Durability.",
    "fullText": "Aspect: Adamant\nInitial. When a physical attack hits a Fell, prevent Bonus damage equal to the lorebound owner's Durability.\nBranching, keep one: Deal the prevented damage to the attacker. OR After the Bonus is prevented, also prevent the Base damage.\nCrown, keep one: Deal the prevented damage to every enemy in the lorebound's Mobility range. OR Prevent all of the incoming damage instead.",
    "imageUrl": "",
    "payload": "{\"meta\": {\"world\": \"Thaloryn\", \"role\": \"Shrugs off a blow's bite and sends it back at the striker.\", \"archetype\": \"mitigation\", \"aspectName\": \"Adamant\", \"initial\": \"When a physical attack hits a Fell, prevent Bonus damage equal to the lorebound owner's Durability.\", \"branches\": [\"Deal the prevented damage to the attacker.\", \"After the Bonus is prevented, also prevent the Base damage.\"], \"crowns\": [\"Deal the prevented damage to every enemy in the lorebound's Mobility range.\", \"Prevent all of the incoming damage instead.\"], \"creator\": \"Skyvault Studios\"}}"
  },
  {
    "forgeKey": "bondforge",
    "kind": "bond",
    "creationName": "The Runesteed",
    "canonStatus": "canon",
    "voteCount": 0,
    "creatorName": "Skyvault Studios",
    "shorthand": "When a Fell gains a Combat Effect, negate it.",
    "fullText": "Aspect: Unbind\nInitial. When a Fell gains a Combat Effect, negate it.\nBranching, keep one: Apply the negated Combat Effect to the one who added it. OR Heal the targeted Fell's Vitality equal to the lorebound owner's Vigor.\nCrown, keep one: Apply Manifested (create a temporary barrier) in an empty space adjacent to the target. OR The targeted Fell may move up to its Mobility.",
    "imageUrl": "",
    "payload": "{\"meta\": {\"world\": \"Valoria\", \"role\": \"Breaks a Combat Effect off a Fell and wards what comes next.\", \"archetype\": \"restoration\", \"aspectName\": \"Unbind\", \"initial\": \"When a Fell gains a Combat Effect, negate it.\", \"branches\": [\"Apply the negated Combat Effect to the one who added it.\", \"Heal the targeted Fell's Vitality equal to the lorebound owner's Vigor.\"], \"crowns\": [\"Apply Manifested (create a temporary barrier) in an empty space adjacent to the target.\", \"The targeted Fell may move up to its Mobility.\"], \"creator\": \"Skyvault Studios\"}}"
  },
  {
    "forgeKey": "bondforge",
    "kind": "bond",
    "creationName": "The Slipfang",
    "canonStatus": "canon",
    "voteCount": 0,
    "creatorName": "Skyvault Studios",
    "shorthand": "When a Fell rolls to Evade, that roll is a Lucky Roll.",
    "fullText": "Aspect: Elude\nInitial. When a Fell rolls to Evade, that roll is a Lucky Roll.\nBranching, keep one: The attacker's Precision becomes 0 for that attack. OR The Fell adds the lorebound owner's Evasion to its own for that attack.\nCrown, keep one: Add a second Lucky die to that Evade. OR The attacker's attack roll against that Fell is an Unlucky Roll.",
    "imageUrl": "",
    "payload": "{\"meta\": {\"world\": \"Avemriol\", \"role\": \"Slips a Fell out of an attack's path.\", \"archetype\": \"negation\", \"aspectName\": \"Elude\", \"initial\": \"When a Fell rolls to Evade, that roll is a Lucky Roll.\", \"branches\": [\"The attacker's Precision becomes 0 for that attack.\", \"The Fell adds the lorebound owner's Evasion to its own for that attack.\"], \"crowns\": [\"Add a second Lucky die to that Evade.\", \"The attacker's attack roll against that Fell is an Unlucky Roll.\"], \"creator\": \"Skyvault Studios\"}}"
  },
  {
    "forgeKey": "bondforge",
    "kind": "bond",
    "creationName": "The Solmera",
    "canonStatus": "canon",
    "voteCount": 0,
    "creatorName": "Skyvault Studios",
    "shorthand": "When an enemy attacks a Fell, deal 1d6 Base damage to the attacker.",
    "fullText": "Aspect: Pyre\nInitial. When an enemy attacks a Fell, deal 1d6 Base damage to the attacker.\nBranching, keep one: Apply a Combat Effect at random to the attacker. OR Deal 1d6 Base damage again.\nCrown, keep one: Apply the Ignited Affliction to the attacker. OR Apply the Frozen Affliction to the attacker.",
    "imageUrl": "",
    "payload": "{\"meta\": {\"world\": \"Oroniel\", \"role\": \"Burns any foe that dares strike a Fell.\", \"archetype\": \"control\", \"aspectName\": \"Pyre\", \"initial\": \"When an enemy attacks a Fell, deal 1d6 Base damage to the attacker.\", \"branches\": [\"Apply a Combat Effect at random to the attacker.\", \"Deal 1d6 Base damage again.\"], \"crowns\": [\"Apply the Ignited Affliction to the attacker.\", \"Apply the Frozen Affliction to the attacker.\"], \"creator\": \"Skyvault Studios\"}}"
  },
  {
    "forgeKey": "bondforge",
    "kind": "bond",
    "creationName": "The Thistlewing",
    "canonStatus": "canon",
    "voteCount": 0,
    "creatorName": "Skyvault Studios",
    "shorthand": "When a target's Tier 1 spell or ability resolves, create a rune for the spell or a trap for the ability in the lorebound owner's inventory.",
    "fullText": "Aspect: Snare\nInitial. When a target's Tier 1 spell or ability resolves, create a rune for the spell or a trap for the ability in the lorebound owner's inventory.\nBranching, keep one: Upgrade the capture to any spell or ability of your choosing in the next highest Tier. OR Create a second copy of the rune or trap.\nCrown, keep one: Upgrade the capture to any spell or ability of your choosing in the next highest Tier. OR Create a second copy of the rune or trap.",
    "imageUrl": "",
    "payload": "{\"meta\": {\"world\": \"Sylvanoth\", \"role\": \"Snares a spent spell or ability into a rune or trap.\", \"archetype\": \"retort\", \"aspectName\": \"Snare\", \"initial\": \"When a target's Tier 1 spell or ability resolves, create a rune for the spell or a trap for the ability in the lorebound owner's inventory.\", \"branches\": [\"Upgrade the capture to any spell or ability of your choosing in the next highest Tier.\", \"Create a second copy of the rune or trap.\"], \"crowns\": [\"Upgrade the capture to any spell or ability of your choosing in the next highest Tier.\", \"Create a second copy of the rune or trap.\"], \"creator\": \"Skyvault Studios\"}}"
  },
  {
    "forgeKey": "bondforge",
    "kind": "bond",
    "creationName": "The Vixel",
    "canonStatus": "canon",
    "voteCount": 0,
    "creatorName": "Skyvault Studios",
    "shorthand": "When a Fell is targeted, apply a Movement Combat Effect of your choice to that Fell.",
    "fullText": "Aspect: Veer\nInitial. When a Fell is targeted, apply a Movement Combat Effect of your choice to that Fell.\nBranching, keep one: Also apply the Combat Effect to one other target within range. OR That Fell is Restored (gains 1 Charge).\nCrown, keep one: Apply a second Combat Effect at random to the enemy targeting the Fell. OR Remove an Affliction at random from the targeted Fell.",
    "imageUrl": "",
    "payload": "{\"meta\": {\"world\": \"Wildermire\", \"role\": \"Shifts a targeted Fell out of harm's way.\", \"archetype\": \"control\", \"aspectName\": \"Veer\", \"initial\": \"When a Fell is targeted, apply a Movement Combat Effect of your choice to that Fell.\", \"branches\": [\"Also apply the Combat Effect to one other target within range.\", \"That Fell is Restored (gains 1 Charge).\"], \"crowns\": [\"Apply a second Combat Effect at random to the enemy targeting the Fell.\", \"Remove an Affliction at random from the targeted Fell.\"], \"creator\": \"Skyvault Studios\"}}"
  },
  {
    "forgeKey": "bondforge",
    "kind": "bond",
    "creationName": "The Worgar",
    "canonStatus": "canon",
    "voteCount": 0,
    "creatorName": "Skyvault Studios",
    "shorthand": "When a Fell takes damage from an attack or spell, manifest a Skyvault Shard in the lorebound owner's inventory.",
    "fullText": "Aspect: Reap\nInitial. When a Fell takes damage from an attack or spell, manifest a Skyvault Shard in the lorebound owner's inventory.\nBranching, keep one: Heal that Fell's Vitality equal to the lorebound owner's Renewal. OR Manifest a second shard in the targeted Fell's inventory.\nCrown, keep one: Double the number of shards manifested. OR Destroy any number of Skyvault Shards and deal Base damage to the attacker for each one destroyed.",
    "imageUrl": "",
    "payload": "{\"meta\": {\"world\": \"Elysara\", \"role\": \"Reaps a Skyvault Shard from every wound a Fell takes.\", \"archetype\": \"restoration\", \"aspectName\": \"Reap\", \"initial\": \"When a Fell takes damage from an attack or spell, manifest a Skyvault Shard in the lorebound owner's inventory.\", \"branches\": [\"Heal that Fell's Vitality equal to the lorebound owner's Renewal.\", \"Manifest a second shard in the targeted Fell's inventory.\"], \"crowns\": [\"Double the number of shards manifested.\", \"Destroy any number of Skyvault Shards and deal Base damage to the attacker for each one destroyed.\"], \"creator\": \"Skyvault Studios\"}}"
  },
  {
    "forgeKey": "bondforge",
    "kind": "bond",
    "creationName": "The Xenophis",
    "canonStatus": "canon",
    "voteCount": 0,
    "creatorName": "Skyvault Studios",
    "shorthand": "When a Fell takes damage from any source, it becomes Obscured (enemies cannot see or target it until it deals damage or the end of its next round).",
    "fullText": "Aspect: Umbra\nInitial. When a Fell takes damage from any source, it becomes Obscured (enemies cannot see or target it until it deals damage or the end of its next round).\nBranching, keep one: Apply a Movement Combat Effect of your choice to that Fell. OR Deal the damage taken back to the source.\nCrown, keep one: Also apply Obscured to another Fell within the lorebound's Mobility range. OR Apply a second Movement Combat Effect to the Fell.",
    "imageUrl": "",
    "payload": "{\"meta\": {\"world\": \"Crixalis\", \"role\": \"Wraps a wounded Fell in shadow, beyond an enemy's sight.\", \"archetype\": \"control\", \"aspectName\": \"Umbra\", \"initial\": \"When a Fell takes damage from any source, it becomes Obscured (enemies cannot see or target it until it deals damage or the end of its next round).\", \"branches\": [\"Apply a Movement Combat Effect of your choice to that Fell.\", \"Deal the damage taken back to the source.\"], \"crowns\": [\"Also apply Obscured to another Fell within the lorebound's Mobility range.\", \"Apply a second Movement Combat Effect to the Fell.\"], \"creator\": \"Skyvault Studios\"}}"
  }
];
