// backend/forge.web.js
// Wix Velo web module (modern .web.js format). Frontend page code imports and calls these.
// This is the security boundary: every submission is re-validated here and written with
// elevated permission, so the client embed can never write to a collection directly.
//
// Shared across every forge. SigilForge uses it now, future forges reuse it unchanged.
// Companion file: backend/rules.js (generated by scripts/build.js), added as a plain .js.

import { Permissions, webMethod } from 'wix-web-module';
import wixData from 'wix-data';
import { currentMember } from 'wix-members-backend';
import { validate } from 'backend/rules.js';

const LOREMASTER_FORGES = ['foeforge', 'sagaforge'];
const LOREMASTER_ROLE_TITLES = ['Loremaster', 'LoreKeeper'];

export const getForgeDefinition = webMethod(Permissions.Anyone, async (forgeKey) => {
  const cfg = await wixData.query('ForgeConfig')
    .eq('forgeKey', forgeKey).eq('active', true).find();
  if (!cfg.items.length) throw new Error('Unknown or inactive forge: ' + forgeKey);
  const config = cfg.items[0];

  const comps = await wixData.query('ForgeComponents')
    .eq('forgeKey', forgeKey).eq('active', true)
    .ascending('sortOrder').limit(1000).find();

  return {
    forgeKey: forgeKey,
    version: config.version,
    rules: parse(config.rules, {}),
    componentGroups: parse(config.componentGroups, []),
    outputTemplates: parse(config.outputTemplates, {}),
    submitTarget: config.submitTarget,
    components: comps.items.map(function (c) {
      return {
        componentId: c.componentId,
        groupId: c.groupId,
        label: c.label,
        cost: c.cost,
        tier: c.tier,
        categories: parse(c.categories, []),
        stats: parse(c.stats, {}),
        description: c.description,
        imageUrl: c.imageUrl
      };
    })
  };
});

export const submitCreation = webMethod(Permissions.SiteMember, async (forgeKey, payload, ownerMemberId) => {
  const member = await currentMember.getMember({ fieldsets: ['FULL'] });
  if (!member) return { ok: false, errors: ['You need to be signed in.'] };

  const allowed = await canUseForge(forgeKey, member);
  if (!allowed) return { ok: false, errors: ['Your role cannot use this forge.'] };

  const def = await getForgeDefinition(forgeKey);
  const result = validate(payload, def);
  if (!result.legal) return { ok: false, errors: result.errors };

  const owner = ownerMemberId || member._id;
  const rendered = renderOutput(payload, def, result);

  const legality = {
    tier: payload.tier,
    form: payload.form,
    mode: payload.mode || 'weapon',
    cost: result.totals.cost,
    budget: result.totals.budget,
    inlays: result.totals.inlays,
    afflictions: result.totals.afflictions,
    valid: true
  };

  const record = {
    forgeKey: forgeKey,
    definitionVersion: def.version,
    kind: payload.kind === 'foe' ? 'foe' : 'character',
    creationName: payload.title || (forgeKey + ' build'),
    creatorMemberId: member._id,
    creatorName: displayName(member),
    ownerMemberId: owner,
    worldId: payload.worldId || null,
    payload: JSON.stringify(payload),
    shorthand: payload.shorthand || rendered.shorthand,
    fullText: payload.fullText || rendered.full,
    legality: JSON.stringify(legality),
    creatorNote: payload.creatorNote || '',
    fingerprint: fingerprintOf(forgeKey, payload),
    basedOn: payload.basedOn || null,
    imageUrl: payload.imageUrl || null,
    canonStatus: 'submitted',
    voteCount: 0
  };

  const saved = await wixData.insert(def.submitTarget, record, { suppressAuth: true });
  return { ok: true, creationId: saved._id, warnings: result.warnings };
});

// Browse and remix read. Powers the Ledger and the basedOn lineage.
export const getCreations = webMethod(Permissions.Anyone, async (forgeKey, opts) => {
  opts = opts || {};
  let q = wixData.query('Creations').eq('forgeKey', forgeKey);
  if (opts.canonStatus) q = q.eq('canonStatus', opts.canonStatus);
  if (opts.creatorMemberId) q = q.eq('creatorMemberId', opts.creatorMemberId);
  if (opts.kind) q = q.eq('kind', opts.kind);
  q = q.descending('_createdDate').limit(Math.min(opts.limit || 50, 100));
  const res = await q.find({ suppressAuth: true });
  return res.items.map(function (s) {
    return {
      creationId: s._id, creationName: s.creationName, creatorName: s.creatorName,
      canonStatus: s.canonStatus, voteCount: s.voteCount, kind: s.kind,
      shorthand: s.shorthand, imageUrl: s.imageUrl, fingerprint: s.fingerprint,
      payload: s.payload
    };
  });
});

// Overlap check. The tool calls this before submit and warns when a near-identical
// build already exists, so duplicates do not reach the vote or the LoreMaster.
export const findSimilar = webMethod(Permissions.SiteMember, async (forgeKey, payload) => {
  const fp = fingerprintOf(forgeKey, payload);
  const hits = await wixData.query('Creations')
    .eq('forgeKey', forgeKey).eq('fingerprint', fp).limit(10).find({ suppressAuth: true });
  return hits.items.map(function (s) {
    return { creationId: s._id, creationName: s.creationName, canonStatus: s.canonStatus, creatorName: s.creatorName };
  });
});


// One vote per member toward Gate 1 canonization. Increments voteCount and records the
// voter so a member cannot vote twice. Degrades to a plain increment if the optional
// voters field is not on the collection yet.
export const castVote = webMethod(Permissions.SiteMember, async (forgeKey, creationId) => {
  const member = await currentMember.getMember();
  if (!member) return { ok: false, signin: true };
  if (!creationId) return { ok: false, error: 'No creation given.' };

  let rec;
  try { rec = await wixData.get('Creations', creationId, { suppressAuth: true }); }
  catch (e) { return { ok: false, error: 'That creation was not found.' }; }
  if (!rec || rec.forgeKey !== forgeKey) return { ok: false, error: 'That creation was not found.' };

  const voters = Array.isArray(rec.voters) ? rec.voters : [];
  if (voters.indexOf(member._id) !== -1) {
    return { ok: true, already: true, voteCount: rec.voteCount || 0 };
  }

  const next = (rec.voteCount || 0) + 1;
  try {
    await wixData.update('Creations',
      { _id: creationId, voteCount: next, voters: voters.concat([member._id]) },
      { suppressAuth: true });
  } catch (e) {
    // voters field may not exist; fall back to a bare tally so voting still works
    try { await wixData.update('Creations', { _id: creationId, voteCount: next }, { suppressAuth: true }); }
    catch (e2) { return { ok: false, error: 'The vote could not be saved.' }; }
  }
  return { ok: true, voteCount: next };
});

async function canUseForge(forgeKey, member) {
  if (LOREMASTER_FORGES.indexOf(forgeKey) === -1) return true;
  const roles = await currentMember.getRoles();
  return roles.some(function (r) { return LOREMASTER_ROLE_TITLES.indexOf(r.title) !== -1; });
}

function fingerprintOf(forgeKey, payload) {
  const ids = (payload.selections || []).slice().sort();
  return forgeKey + ':' + (payload.kind === 'foe' ? 'foe' : 'character') +
    ':T' + (payload.tier || 1) + 'F' + (payload.form || 1) + ':' + ids.join('+');
}

function displayName(member) {
  if (member.profile && member.profile.nickname) return member.profile.nickname;
  if (member.contactDetails && member.contactDetails.firstName) return member.contactDetails.firstName;
  return 'A Fell';
}

function renderOutput(payload, def, result) {
  const labels = (payload.selections || []).map(function (id) {
    const c = def.components.filter(function (x) { return x.componentId === id; })[0];
    return c ? c.label : id;
  });
  return {
    shorthand: 'T' + payload.tier + 'F' + payload.form + ' [' + labels.join(', ') + ']',
    full: 'Tier ' + payload.tier + ', Form ' + payload.form + '. ' +
          'Components: ' + labels.join(', ') + '. ' +
          'Spent ' + result.totals.cost + ' of ' + result.totals.budget[1] + '.'
  };
}

function parse(s, fallback) {
  if (s && typeof s === 'object') return s;
  try { return JSON.parse(s || ''); } catch (e) { return fallback; }
}
