// backend/forge.web.js
// Wix Velo web module (modern .web.js format). Frontend page code imports and calls these.
// This is the security boundary: every submission is re-validated here and written with
// elevated permission, so the client embed can never write to a collection directly.
//
// Shared across every forge. SigilForge uses it now, future forges reuse it unchanged.
// Companion file: backend/rules.js (generated by scripts/build.js), added as a plain .js.

import { Permissions, webMethod } from 'wix-web-module';
import wixData from 'wix-data';
import { currentMember } from 'wix-members-backend';
import { validate } from 'backend/rules.js';

const LOREMASTER_FORGES = ['foeforge', 'sagaforge'];
const LOREMASTER_ROLE_TITLES = ['Loremaster', 'LoreKeeper'];

export const getForgeDefinition = webMethod(Permissions.Anyone, async (forgeKey) => {
  const cfg = await wixData.query('ForgeConfig')
    .eq('forgeKey', forgeKey).eq('active', true).find();
  if (!cfg.items.length) throw new Error('Unknown or inactive forge: ' + forgeKey);
  const config = cfg.items[0];

  const comps = await wixData.query('ForgeComponents')
    .eq('forgeKey', forgeKey).eq('active', true)
    .ascending('sortOrder').limit(1000).find();

  return {
    forgeKey: forgeKey,
    version: config.version,
    rules: parse(config.rules, {}),
    componentGroups: parse(config.componentGroups, []),
    outputTemplates: parse(config.outputTemplates, {}),
    submitTarget: config.submitTarget,
    components: comps.items.map(function (c) {
      return {
        componentId: c.componentId,
        groupId: c.groupId,
        label: c.label,
        cost: c.cost,
        tier: c.tier,
        categories: parse(c.categories, []),
        stats: parse(c.stats, {}),
        description: c.description,
        imageUrl: c.imageUrl
      };
    })
  };
});

export const submitCreation = webMethod(Permissions.SiteMember, async (forgeKey, payload, ownerMemberId) => {
  const member = await currentMember.getMember({ fieldsets: ['FULL'] });
  if (!member) return { ok: false, errors: ['You need to be signed in.'] };

  const allowed = await canUseForge(forgeKey, member);
  if (!allowed) return { ok: false, errors: ['Your role cannot use this forge.'] };

  const def = await getForgeDefinition(forgeKey);
  const result = validate(payload, def);
  if (!result.legal) return { ok: false, errors: result.errors };

  const owner = ownerMemberId || member._id;
  const rendered = renderOutput(payload, def, result);

  const legality = {
    tier: payload.tier,
    form: payload.form,
    mode: payload.mode || 'weapon',
    cost: result.totals.cost,
    budget: result.totals.budget,
    inlays: result.totals.inlays,
    afflictions: result.totals.afflictions,
    valid: true
  };

  const record = {
    forgeKey: forgeKey,
    definitionVersion: def.version,
    kind: payload.kind || 'character',
    creationName: payload.title || (forgeKey + ' build'),
    creatorMemberId: member._id,
    creatorName: displayName(member),
    ownerMemberId: owner,
    worldId: payload.worldId || null,
    payload: JSON.stringify(payload),
    shorthand: payload.shorthand || rendered.shorthand,
    fullText: payload.fullText || rendered.full,
    legality: JSON.stringify(legality),
    creatorNote: payload.creatorNote || '',
    fingerprint: fingerprintOf(forgeKey, payload),
    basedOn: payload.basedOn || null,
    imageUrl: payload.imageUrl || null,
    canonStatus: 'submitted',
    voteCount: 0
  };

  const saved = await wixData.insert(def.submitTarget, record, { suppressAuth: true });
  return { ok: true, creationId: saved._id, warnings: result.warnings };
});

// Build a legal SigilForge act from real components. The caller (FoeForge) supplies
// only tier, type (ability or spell), and a one word flavor. The mechanics, cost, and
// effect come from the actual component catalog and the shared validator, never invented.
export const buildLegalAct = webMethod(Permissions.SiteMember, async (tier, type, flavor) => {
  tier = Math.max(1, Math.min(3, Number(tier) || 1));
  const kind = type === 'spell' ? 'spell' : 'ability';
  const def = await getForgeDefinition('sigilforge');
  const has = function (id) { return def.components.some(function (c) { return c.componentId === id; }); };
  const labelOf = function (id) { const c = def.components.filter(function (x) { return x.componentId === id; })[0]; return c ? c.label : id; };

  let descById = {};
  try {
    const cr = await wixData.query('ForgeComponents').eq('forgeKey', 'sigilforge').eq('active', true).limit(1000).find();
    cr.items.forEach(function (c) { descById[c.componentId] = c.description || ''; });
  } catch (e) {}

  const FLAVORS = [
    { keys: ['fire', 'burn', 'ember', 'ash', 'cinder', 'flame', 'scorch', 'pyre'], reg: 'Ignited*', t1: 'Crushed' },
    { keys: ['fear', 'dread', 'terror', 'horror', 'panic'], reg: 'Terrorized*', t1: 'Crushed' },
    { keys: ['bleed', 'blood', 'gore', 'hemorrhage'], reg: 'Bleeding*', major: 'Lacerated*', t1: 'Cleaved' },
    { keys: ['rot', 'decay', 'disease', 'plague', 'sick', 'fester', 'blight', 'pox'], reg: 'Infected*', major: 'Plagued*', t1: 'Crushed' },
    { keys: ['mind', 'confuse', 'daze', 'bewilder', 'scramble'], reg: 'Disoriented*', t1: 'Crushed' },
    { keys: ['mad', 'stupefy', 'dumb', 'witless', 'addle'], reg: 'Witless*', t1: 'Crushed' },
    { keys: ['curse', 'hex', 'doom', 'jinx'], reg: 'Jinxed*', major: 'Accursed*', t1: 'Crushed' },
    { keys: ['luck', 'fortune', 'chance', 'fate'], reg: 'Unlucky*', t1: 'Crushed' },
    { keys: ['bind', 'root', 'snare', 'web', 'entangle', 'grasp', 'hold'], reg: 'Immobilized*', major: 'Ensnared*', t1: 'Crushed' },
    { keys: ['slow', 'hinder', 'mire', 'sluggish', 'tar'], reg: 'Impeded*', t1: 'Crushed' },
    { keys: ['weak', 'sap', 'enfeeble', 'frail'], reg: 'Diminished*', major: 'Enfeebled*', t1: 'Crushed' },
    { keys: ['frost', 'cold', 'ice', 'freeze', 'rime', 'winter', 'chill'], reg: 'Immobilized*', major: 'Frozen*', t1: 'Crushed' },
    { keys: ['poison', 'venom', 'toxic', 'toxin'], reg: 'Tainted*', t1: 'Crushed' },
    { keys: ['maim', 'mangle', 'rip', 'tear', 'shred'], reg: 'Mangled*', major: 'Crippled*', t1: 'Cleaved' },
    { keys: ['light', 'blind', 'dazzle', 'flash', 'glare', 'radiant'], reg: 'Dazzled*', t1: 'Pierced' },
    { keys: ['shadow', 'dark', 'veil', 'stealth', 'hidden', 'obscure'], reg: 'Masked*', t1: 'Crushed' },
    { keys: ['cut', 'slash', 'rend', 'sever', 'blade'], reg: 'Slashed*', major: 'Lacerated*', t1: 'Cleaved' },
    { keys: ['blunt', 'bruise', 'smash', 'crush', 'hammer'], reg: 'Bruised*', t1: 'Crushed' },
    { keys: ['wither', 'age', 'husk', 'drain', 'leech'], reg: 'Withered*', t1: 'Crushed' },
    { keys: ['vulnerable', 'expose', 'weakpoint', 'open'], reg: 'Vulnerable*', t1: 'Exposed' },
    { keys: ['strip', 'sunder', 'armor', 'unclad', 'bare'], reg: 'Unclad*', major: 'Disarmed*', t1: 'Pierced' },
    { keys: ['dispel', 'antimagic', 'silence', 'null', 'unmake'], reg: 'Disenchanted*', major: 'Nullified*', t1: 'Crushed' },
    { keys: ['frenzy', 'rage', 'berserk', 'fury', 'wrath'], reg: 'Frenzied*', t1: 'Crushed' },
    { keys: ['clumsy', 'fumble', 'inept', 'graceless'], reg: 'Inept*', t1: 'Crushed' },
    { keys: ['mark', 'hunt', 'track', 'prey', 'quarry'], reg: 'Hunted*', t1: 'Crushed' },
    { keys: ['joint', 'dislocate', 'disable', 'wrench'], reg: 'Dislocated*', t1: 'Crushed' },
    { keys: ['stymie', 'block', 'foil', 'thwart', 'baffle'], reg: 'Stymied*', t1: 'Crushed' },
    { keys: ['corrupt', 'defile', 'taint', 'profane'], reg: 'Tainted*', major: 'Harvested*', t1: 'Crushed' },
    { keys: ['shatter', 'fragment', 'break', 'crack', 'splinter'], reg: 'Fragmented*', t1: 'Shattered' },
    { keys: ['harry', 'persecute', 'torment', 'hound'], reg: 'Persecuted*', t1: 'Crushed' },
    { keys: ['reap', 'harvest', 'soul', 'cull'], reg: 'Reapt*', major: 'Harvested*', t1: 'Crushed' },
    { keys: ['spoil', 'vitiate', 'sour'], reg: 'Vitiated*', t1: 'Crushed' },
    { keys: ['restrict', 'constrain', 'tighten', 'cinch'], reg: 'Impeded*', major: 'Constrained*', t1: 'Crushed' },
    { keys: ['stagger', 'stun', 'reel', 'daze'], reg: 'Staggered*', t1: 'Crushed' }
  ];
  const flv = String(flavor || '').toLowerCase();
  let g = null;
  for (let i = 0; i < FLAVORS.length && !g; i++) {
    for (let k = 0; k < FLAVORS[i].keys.length; k++) {
      if (flv.indexOf(FLAVORS[i].keys[k]) !== -1) { g = FLAVORS[i]; break; }
    }
  }
  if (!g) g = { reg: 'Staggered*', t1: 'Crushed' };
  const reg = has(g.reg) ? g.reg : 'Staggered*';
  const major = (g.major && has(g.major)) ? g.major : null;
  const t1 = has(g.t1) ? g.t1 : 'Crushed';

  const candidates = {
    1: [['Standard Damage', 'One Target', t1], ['Standard Damage', 'One Target', 'Crushed']],
    2: [['Standard Damage', 'One Target', reg], ['Standard Damage', 'One Target', 'Exposed', 'Crushed']],
    3: major
      ? [['Standard Damage', 'One Target', major, 'Exposed'], ['Standard Damage', 'One Target', reg, 'Exposed'], ['Double Standard Damage', 'One Target', 'Exposed', 'Pierced']]
      : [['Standard Damage', 'One Target', reg, 'Exposed'], ['Double Standard Damage', 'One Target', 'Exposed', 'Pierced']]
  }[tier];

  const byTier = (def.rules.budgets && def.rules.budgets.byTier) || {};
  const band = byTier[String(tier)] || [1, 2];

  let sel = null, res = null;
  for (let i = 0; i < candidates.length; i++) {
    const ids = candidates[i].filter(has);
    const payload = { tier: tier, form: tier, mode: 'weapon', kind: kind, selections: ids };
    const r = validate(payload, def);
    const c = r.totals.cost;
    if (r.legal && c >= band[0] && c <= band[1]) { sel = ids; res = r; break; }
  }
  if (!sel) {
    sel = ['Standard Damage', 'One Target'].filter(has);
    res = validate({ tier: tier, form: tier, mode: 'weapon', kind: kind, selections: sel }, def);
  }

  const labels = sel.map(labelOf);
  const descLines = sel.map(function (id) { const d = descById[id] || ''; return d ? (labelOf(id) + ': ' + d) : labelOf(id); });
  const fullText = 'Tier ' + tier + ' ' + kind + '. ' + descLines.join(' ');
  const shorthand = 'T' + tier + ' [' + labels.join(', ') + ']';

  const payload = { tier: tier, form: tier, mode: 'weapon', kind: kind, selections: sel,
    cost: res.totals.cost, shorthand: shorthand, fullText: fullText };
  return { ok: !!res.legal, payload: payload, cost: res.totals.cost, effect: fullText, shorthand: shorthand, errors: res.errors || [] };
});

// Private Foe saves. Stored in Creations under a separate forgeKey so they never
// surface in the Pentifax ledger, which reads forgeKey 'foeforge'. The whole tool
// state, including forged acts kept to the Foe, rides along in the payload.
const PRIVATE_FOE_KEY = 'foeforge.private';

export const saveFoe = webMethod(Permissions.SiteMember, async (payload) => {
  const member = await currentMember.getMember();
  if (!member) return { ok: false, errors: ['Sign in to save a Foe.'] };
  payload = payload || {};
  const rec = {
    forgeKey: PRIVATE_FOE_KEY,
    kind: 'foe',
    creationName: String(payload.name || 'Unnamed Foe').slice(0, 120),
    creatorMemberId: member._id,
    creatorName: displayName(member),
    ownerMemberId: member._id,
    payload: JSON.stringify(payload),
    shorthand: (payload.shatterRating || '') + ' ' + (payload.build || ''),
    fullText: '',
    canonStatus: 'private',
    voteCount: 0
  };
  let saved = null;
  if (payload.foeId) {
    let existing = null;
    try { existing = await wixData.get('Creations', payload.foeId); } catch (e) { existing = null; }
    if (existing && existing.creatorMemberId === member._id && existing.forgeKey === PRIVATE_FOE_KEY) {
      existing.creationName = rec.creationName;
      existing.payload = rec.payload;
      existing.shorthand = rec.shorthand;
      saved = await wixData.update('Creations', existing, { suppressAuth: true });
    }
  }
  if (!saved) saved = await wixData.insert('Creations', rec, { suppressAuth: true });
  return { ok: true, foeId: saved._id };
});

export const myFoes = webMethod(Permissions.SiteMember, async () => {
  const member = await currentMember.getMember();
  if (!member) return [];
  const res = await wixData.query('Creations')
    .eq('forgeKey', PRIVATE_FOE_KEY).eq('creatorMemberId', member._id)
    .descending('_updatedDate').limit(50).find({ suppressAuth: true });
  return res.items.map(function (r) {
    return { foeId: r._id, name: r.creationName, shorthand: r.shorthand, payload: r.payload, updated: r._updatedDate };
  });
});

export const deleteFoe = webMethod(Permissions.SiteMember, async (foeId) => {
  const member = await currentMember.getMember();
  if (!member) return { ok: false };
  let ex = null;
  try { ex = await wixData.get('Creations', foeId); } catch (e) { ex = null; }
  if (ex && ex.creatorMemberId === member._id && ex.forgeKey === PRIVATE_FOE_KEY) {
    await wixData.remove('Creations', foeId, { suppressAuth: true });
    return { ok: true };
  }
  return { ok: false };
});

// Browse and remix read. Powers the Ledger and the basedOn lineage.
export const getCreations = webMethod(Permissions.Anyone, async (forgeKey, opts) => {
  opts = opts || {};
  let q = wixData.query('Creations').eq('forgeKey', forgeKey);
  if (opts.canonStatus) q = q.eq('canonStatus', opts.canonStatus);
  if (opts.creatorMemberId) q = q.eq('creatorMemberId', opts.creatorMemberId);
  if (opts.kind) q = q.eq('kind', opts.kind);
  q = q.descending('_createdDate').limit(Math.min(opts.limit || 50, 100));
  const res = await q.find({ suppressAuth: true });
  return res.items.map(function (s) {
    return {
      creationId: s._id, creationName: s.creationName, creatorName: s.creatorName,
      canonStatus: s.canonStatus, voteCount: s.voteCount, kind: s.kind,
      shorthand: s.shorthand, fullText: s.fullText, imageUrl: s.imageUrl, fingerprint: s.fingerprint,
      payload: s.payload
    };
  });
});

// Generic catalog read. Any forge can pull a content collection (canon set) by id.
// Sorts by displayOrder when present. Wix image fields are converted to URLs for the iframe.
function wixImg(v) {
  if (typeof v === 'string' && v.indexOf('wix:image://') === 0) {
    const parts = v.slice(12).split('/');
    return parts[1] ? ('https://static.wixstatic.com/media/' + parts[1]) : '';
  }
  return v;
}
export const getCatalog = webMethod(Permissions.Anyone, async (collectionId, opts) => {
  opts = opts || {};
  const lim = Math.min(opts.limit || 300, 1000);
  let res;
  try { res = await wixData.query(collectionId).ascending('displayOrder').limit(lim).find({ suppressAuth: true }); }
  catch (e) { res = await wixData.query(collectionId).limit(lim).find({ suppressAuth: true }); }
  return res.items.map(function (row) {
    const out = {};
    Object.keys(row).forEach(function (k) { out[k] = wixImg(row[k]); });
    return out;
  });
});

// Overlap check. The tool calls this before submit and warns when a near-identical
// build already exists, so duplicates do not reach the vote or the LoreMaster.
export const findSimilar = webMethod(Permissions.SiteMember, async (forgeKey, payload) => {
  const fp = fingerprintOf(forgeKey, payload);
  const hits = await wixData.query('Creations')
    .eq('forgeKey', forgeKey).eq('fingerprint', fp).limit(10).find({ suppressAuth: true });
  return hits.items.map(function (s) {
    return { creationId: s._id, creationName: s.creationName, canonStatus: s.canonStatus, creatorName: s.creatorName };
  });
});


// One vote per member toward Gate 1 canonization. Increments voteCount and records the
// voter so a member cannot vote twice. Degrades to a plain increment if the optional
// voters field is not on the collection yet.
export const castVote = webMethod(Permissions.SiteMember, async (forgeKey, creationId) => {
  const member = await currentMember.getMember();
  if (!member) return { ok: false, signin: true };
  if (!creationId) return { ok: false, error: 'No creation given.' };

  let rec;
  try { rec = await wixData.get('Creations', creationId, { suppressAuth: true }); }
  catch (e) { return { ok: false, error: 'That creation was not found.' }; }
  if (!rec || rec.forgeKey !== forgeKey) return { ok: false, error: 'That creation was not found.' };

  const voters = Array.isArray(rec.voters) ? rec.voters : [];
  if (voters.indexOf(member._id) !== -1) {
    return { ok: true, already: true, voteCount: rec.voteCount || 0 };
  }

  const next = (rec.voteCount || 0) + 1;
  try {
    await wixData.update('Creations',
      { _id: creationId, voteCount: next, voters: voters.concat([member._id]) },
      { suppressAuth: true });
  } catch (e) {
    // voters field may not exist; fall back to a bare tally so voting still works
    try { await wixData.update('Creations', { _id: creationId, voteCount: next }, { suppressAuth: true }); }
    catch (e2) { return { ok: false, error: 'The vote could not be saved.' }; }
  }
  return { ok: true, voteCount: next };
});

async function canUseForge(forgeKey, member) {
  if (LOREMASTER_FORGES.indexOf(forgeKey) === -1) return true;
  const roles = await currentMember.getRoles();
  return roles.some(function (r) { return LOREMASTER_ROLE_TITLES.indexOf(r.title) !== -1; });
}

function fingerprintOf(forgeKey, payload) {
  const ids = (payload.selections || []).slice().sort();
  return forgeKey + ':' + (payload.kind === 'foe' ? 'foe' : 'character') +
    ':T' + (payload.tier || 1) + 'F' + (payload.form || 1) + ':' + ids.join('+');
}

function displayName(member) {
  if (member.profile && member.profile.nickname) return member.profile.nickname;
  if (member.contactDetails && member.contactDetails.firstName) return member.contactDetails.firstName;
  return 'A Fell';
}

function renderOutput(payload, def, result) {
  const labels = (payload.selections || []).map(function (id) {
    const c = def.components.filter(function (x) { return x.componentId === id; })[0];
    return c ? c.label : id;
  });
  return {
    shorthand: 'T' + payload.tier + 'F' + payload.form + ' [' + labels.join(', ') + ']',
    full: 'Tier ' + payload.tier + ', Form ' + payload.form + '. ' +
          'Components: ' + labels.join(', ') + '. ' +
          'Spent ' + result.totals.cost + ' of ' + result.totals.budget[1] + '.'
  };
}

function parse(s, fallback) {
  if (s && typeof s === 'object') return s;
  try { return JSON.parse(s || ''); } catch (e) { return fallback; }
}
